### ISSUE TITLE
Pre-training weights loading

### ISSUE THREAD

**Issue by haoyao0131** [LandskapeAI/triplet-attention#12]
Hi,

No matter which definitions that I used for triplet-attention definition, I can't load the pertaining weights.

And could you please let me know which the triplet-attention version that matches the Imagenet Pretraining weights?

**Comment by iyaja** [comment]
Sorry for the trouble. This is because we renamed the module internally after we trained a few models. I just loaded the weights to check, and these [these weights](https://drive.google.com/open?id=1ptKswHzVmULGbE3DuX6vMCjEbqwUvGiG) should work with [this model definition](https://github.com/LandskapeAI/triplet-attention/blob/master/MODELS/triplet_attention.py) if you name the module `pcam` in whatever `nn.Module` you decide to place triplet attention in.

However, there are many factors that could affect the state dict loading, such as the device you are loading the model to, which weights you're loading, and your usage of `nn.DataParallel`, so it's hard to say what went wrong. If you can share your code in some form, we might be able to help resolve the issue.

**Comment by snant** [comment]
excuse me，I have a same problem and can you provide a e-mail that I send my code to you？thanks

**Comment by snant** [comment]
and other question，could i put the triplet_attention location where in the resnet50?

**Comment by iyaja** [comment]
> excuse me，I have a same problem and can you provide a e-mail that I send my code to you？thanks

Sorry for the late reply. You can reach me at aua2@illinois.edu.

> and other question，could i put the triplet_attention location where in the resnet50?

In principle, you can place the triplet attention module after any other pytorch `nn.Module` that returns a tensor of shape `(N, C, H, W)`. Triplet attention is a dimensionality preserving module, so it plays nice with other layers.

That said, the recommended location for triplet attention module is right before the residual connection in each `Bottleneck` module. You can refer to our sample [resnet implementation](https://github.com/LandskapeAI/triplet-attention/blob/master/MODELS/resnet.py).

**Comment by daixiangzi** [comment]
> Hi,
> 
> No matter which definitions that I used for triplet-attention definition, I can't load the pertaining weights.
> 
> And could you please let me know which the triplet-attention version that matches the Imagenet Pretraining weights?

your problem have solved? I met same problem
