### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by daixiangzi** [LandskapeAI/triplet-attention#16]
model = ResidualNet( 'ImageNet', 18, 1000, 'TripletAttention')
state_dict = torch.load("model_best.pth.tar")['state_dict']. #ResNet-18+Triplet Attention(k =3)
model.load_state_dict(state_dict)

Unexpected key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var", "module.bn1.num

other double,
k=3 mean that SpatialGate module kernel size=3?

**Comment by daixiangzi** [comment]
when I add lines:
pred_dict = dict()
for key in state_dict:
        pred_dict[key[7:]] = state_dict[key]
  model.load_state_dict(pred_dict)
error:
Missing key(s) in state_dict: "layer1.0.triplet_attention.ChannelGateH.spatial.conv.weight", "layer1.0.triplet_attention.ChannelGateH.spatial.bn.weigh

**Comment by daixiangzi** [comment]
this weight file seems like resnet50 not resnet18?

**Comment by iyaja** [comment]
> this weight file seems like resnet50, not resnet18?

We just double-checked, and I don't think there's an issue with the actual file names, so I suspect your issue might be coming from elsewhere. The file sizes are also as expected. The most common issue is the actual weight-loading, which happens because we changed our layer/module's name mid-way.

> error:
> Missing key(s) in state_dict: "layer1.0.triplet_attention.ChannelGateH.spatial.conv.weight", "layer1.0.triplet_attention.ChannelGateH.spatial.bn.weigh

It seems like your error message is truncated. Having the whole message might help. But I think this is the weight-loading issue that others have faced in the past. Could you try referring to my replies in #12 and see if that helps resolve your issue?
