### ISSUE TITLE
Improvement of Triple Attention

### ISSUE THREAD

**Issue by Mr-Da-Yang** [LandskapeAI/triplet-attention#18]
1. First of all, thank you very much for the triplet attention. After verification on the ReID task, the effect is really good. The disadvantage is that the running time is slow.
2. Try to use this triplet approach to SE too, the effect is also okay
3.For this feature map, find the mean along the direction of the h channel, then when you look at a certain channel alone, as shown in the figure, the outermost channel with people, when finding the mean, the person’s characteristics are calculated from head to toe. It feels very unreasonable.
Can you talk about the inspiration for doing this, or explain it, I am confused about it
![H}9 70}RGE3`ZKMCDSO2XI5](https://user-images.githubusercontent.com/58104855/109779809-4ce92b80-7c41-11eb-80c8-11472a343ec3.png)

**Comment by iyaja** [comment]
Hi, sorry for the late reply.

> Can you talk about the inspiration for doing this, or explain it, I am confused about it

Sure. The main idea is to use regular convolution-based operations across three different "rotated" copies of the 3D input tensor. We hypothesized that this allows the network to capture cross-dimensional features in a way that regular 2D convolutions could not. For example, if the channel dimension represents time (such as in a video where frames are stacked and passed through a CNN), the network could learn features that correspond to an object moving up and down or side-to-side.

You can find more information about this idea of cross-dimensional interaction, the motivation for our method, and our analysis in [our paper](https://openaccess.thecvf.com/content/WACV2021/html/Misra_Rotate_to_Attend_Convolutional_Triplet_Attention_Module_WACV_2021_paper.html).

**Comment by Mr-Da-Yang** [comment]
Thank you very much for your full response！
What I mean is that this operation is actually a variant of spatial attention. So, have you considered doing the same on channel attention?

**Comment by iyaja** [comment]
> What I mean is that this operation is actually a variant of spatial attention.

Yep, you're right. Triplet Attention applies a variant of CBAM's spatial attention across different permutations of the input.

> So, have you considered doing the same on channel attention?

No, not really. But I suppose this would work as well, to a degree.

As we mention in the paper, one of the main motivations of Triplet Attention is efficiently learning how to extract "cross-dimentional" features. So by using spatial attention, each branch is able to learn features that span across two of the three dimensions.

If you used three channel attention branches, you wouldn't be able to learn those kinds of cross-dimensional feature extractors, since the canonical channel attention only operates across one dimension of a tensor.
